# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

[[constraint]]
  name = "github.com/cosmos/cosmos-sdk"
  version = "0.13.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.0.0"

[[constraint]]
  version = "~0.10.2"
  name = "github.com/tendermint/abci"

[[constraint]]
  version = "~0.7.3"
  source = "github.com/tendermint/go-amino"
  name = "github.com/tendermint/go-wire"

[[constraint]]
  version = "~0.7.1"
  name = "github.com/tendermint/tmlibs"

[[constraint]]
  branch="master"
  name = "github.com/globalsign/mgo"


[prune]
  go-tests = true
  unused-packages = true
